### ISSUE TITLE
bug: clerk auth goes into infinite redirect loop in safari

### ISSUE THREAD

**Issue by aayushchugh** [ayush-that/codejeet#1]
Safari version: `18.1.1 (20619.2.8.11.12)`

![Recording 2024-12-01 at 13 02 49](https://github.com/user-attachments/assets/8f6def27-c383-4e66-bd30-f237887a21e5)

**Comment by ParthRana13** [comment]
same goes with Google chrome Version 131.0.6778.86

**Comment by ayush-that** [comment]
> same goes with Google chrome Version 131.0.6778.86

Both email signup and github signing work fine for me on Google Chrome Version 131.0.6778.109. Can you provide more details?

I'm aware about the incompatibility with Safari. I don't own a Mac so I cannot replicate that, and hence cannot fix that.

**Comment by aayushchugh** [comment]
@ayush-that Somehow it's working now. I think it was because of expired cookies or tokens
