### ISSUE TITLE
Add Progress Bar

### ISSUE THREAD

**Issue by ncjpr04** [ayush-that/codejeet#3]
Add progressbar for showing How much problems have been solved in each catagory easy, medium and hard

**Comment by ayush-that** [comment]
![{5CDDED80-0944-45A8-B8B9-B562BE41D9E2}](https://github.com/user-attachments/assets/185efac5-52c0-4f57-a55e-7e5a2df65dc4)
Added ✌🏻
Thanks for the feature suggestion Nitin
