### ISSUE TITLE
the search provides normal results when correct company name searched but when a company not listed searched then the results shown from page 0 🙄

### ISSUE THREAD

**Issue by ParthRana13** [ayush-that/codejeet#4]
[a28d8103-4e71-4cfb-8e1b-c5f551c1dc0a.webm](https://github.com/user-attachments/assets/554e6659-6dc8-4658-81d8-d2b6dbf3c2ed)

**Comment by mayur1377** [comment]
created a fix for that [here](https://github.com/ayush-that/codejeet/pull/10) .
