### ISSUE TITLE
Add Hindi Videos

### ISSUE THREAD

**Issue by poushan-specforces** [ayush-that/codejeet#5]
Alongside NeetCode being the most popular leetcode solutions channel, there's one hindi channel "codestorywithmik" which provides the best solution explanation (in hindi though). Can those videos be added too alongside neetcodes's videos? Also the website can have a feedback form and the companies associated with a question can be viewed when clicking on the tags section (currently only the company we're searching for is visible).

**Comment by ayush-that** [comment]
We first have to finish adding all English solutions first. 
This we can have in future.
